# Generated by Django 2.0 on 2018-06-26 05:10

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Charitea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
        migrations.AlterField(
            model_name='donation',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='donor'),
        ),
    ]
